### ISSUE TITLE
time support?

### ISSUE THREAD

**Issue by joebordes** [GramThanos/jsCalendar#53]
Hi

The calendar looks very nice.

I was looking for time (HH:MM) support, ideally even with seconds (HH:MM:SS) but I don't see it anywhere. Can you please confirm if it is supported or not?

Thanks!

**Comment by GramThanos** [comment]
Sorry for the late answer. Generally speaking, hours, minutes and seconds are out of the scope of the database.
But, since the Date datatype is supported, you can wrap your string inside a `new Date('String in ISO format')`.

```html
<!-- My calendar element -->
<div id="my-calendar"></div>
<!-- Dynamic create it -->
<script type="text/javascript">
	// Get the element
	var element = document.getElementById("my-calendar");
	// Create the calendar
	var cal = jsCalendar.new(element, new Date('2020-12-28 23:59'));
	cal.select(new Date('2020-12-29 14:30'));
	cal.select(new Date('2020-12-29 15:30'));
	cal.select(new Date('2020-12-30 16:30'));
	console.log("Days selected", cal.getSelected().length); // Days selected 2
</script>
```
Keep in mind that as indicated by the example above, when you select dates, the library will only keep the days and not the times.

**Comment by joebordes** [comment]
I see. A pity, I would have liked to use the library. Anyway, I'll keep an eye on it. Thanks for the answer, have a wonderful weekend.
